version: 2

jobs:
  build_dev:
    docker:
    - image: circleci/node:10
      environment:
        NODE_ENV: production
    steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: true
    - run:
        name: Install Dependencies
        command: |
          npm install
    - run:
        name: Run Webpack
        command: |
          NODE_ENV=production npm run build
    - run:
        name: Login to Heroku Container Registry
        command: |
          docker login --username=$HEROKU_USER --password=$HEROKU_TOKEN registry.heroku.com
    - run:
        name: Build Docker Image
        command: |
          docker build -t registry.heroku.com/flagis-web-ci-demo/web .
    - run:
        name: Push to Heroku Container Registry
        command: |
          docker push registry.heroku.com/flagis-web-ci-demo/web

workflows:
  version: 2
  workflow_dev:
    jobs:
    - build_dev:
        filters:
          branches:
            only: development
